version: '3'
services:
  cenefront:
    container_name: cenefront
    build: .
    env_file:
      - ./.env
    volumes:
      - .:/app
      - cenefrontmodules:/app/node_modules
    ports:
      - "1234:1234"
      - "4321:4321"
    depends_on:
      - ceneback
  ceneback:
    container_name: ceneback
    build: ../ceneback/.
    volumes:
      - ../ceneback:/app:delegated
      - cenebackmodules:/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - cenedata
    command: npm run startdev
    env_file:
      - ../ceneback/.env
  cenedata:
    container_name: cenedata
    image: "mysql:5.6"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=cenedb_dev
    ports:
      - 3306:3306
volumes:
  cenefrontmodules:
  cenebackmodules:
